config/routes.rb
Rails.application.routes.draw do
  get 'checkout/confirm_order'
  get 'home/index'
  #root to product index
  root to: 'products#index'

  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  resources :addresses
  resources :products
  resource :cart, only: [:show] do
    post 'add_product', on: :member
    delete 'remove_product', on: :member
    post 'checkout', on: :member
    delete 'empty', on: :member
  end
  resources :products do
    post 'add_to_cart', on: :member
  end
  resources :cart_products, only: [:show, :create, :edit, :update, :destroy] do
    delete 'remove_product', on: :member
  end
  resources :checkout, only: [] do
    collection do
      get 'confirm_order', to: 'checkout#confirm_order'
      post 'place_order', to: 'checkout#place_order'
    end
  end

  get 'order_confirmation', to: 'checkout#order_confirmation', as: 'order_confirmation'
  get 'checkout/index', to: 'checkout#index', as: 'checkout_index'
  resources :orders
  resources :order_products
  resources :payments
  resources :orders do
    resources :payments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/address.rb
# app/models/address.rb
class Address < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :orders

  # Validations
  validates :address, :city, :state, :country, presence: true

  # Methods
  def full_address
    [address, city, state, country].compact.join(', ')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products

  def add_product(product, quantity)
    cart_product = cart_products.find_by(product_id: product.id)
    if cart_product
      cart_product.quantity += quantity
      cart_product.save
    else
      cart_products.create(product: product, quantity: quantity)
    end
  end
end

app/models/cart_product.rb
# app/models/cart_product.rb
class CartProduct < ApplicationRecord
  before_create :set_quantity
  belongs_to :cart
  belongs_to :product
  
  validates :cart_id, presence: true, uniqueness: { scope: :product_id }
  
  def total_amount
    
    quantity * product.price
  end

  def set_quantity
    quantity = quantity || 1
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  has_many :order_products
  has_one :payment

  attribute :total_amount
  attribute :payment_method

  # Calculate the total amount based on order products
  def calculate_total_amount
    self.total_amount = order_products.sum(&:amount)
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
  end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  # Validations
  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  # Associations
  has_many_attached :images
  has_many :order_products

  # Custom validation for image file types
  validate :images_file_types

  private

  # Validate image file types
  def images_file_types
    return unless images.attached?

    images.each do |image|
      unless image.content_type.in?(%w(image/jpeg image/jpg image/png))
        errors.add(:images, 'must be a JPEG, JPG, or PNG')
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :omniauthable, omniauth_providers: [:google_oauth2, :facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :addresses, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :payments, through: :orders, dependent: :destroy

  # Validations
  validates :name, :phone_number, presence: true
  validates :role, presence: true, inclusion: { in: %w(admin customer) }

  # Enums
  enum role: { admin: 'admin', customer: 'customer' }

  # Methods
  def admin?
    role == 'admin'
  end

  def customer?
    role == 'customer'
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :add_product, :checkout, :empty]

  def show
    @cart_products = @cart.cart_products.includes(:product)
    @total_amount = calculate_total_amount(@cart_products)
  end

  def add_product
    product = Product.find(params[:product_id])
    quantity = params[:quantity].to_i || 1
    @cart.add_product(product, quantity)
    redirect_to cart_path
  end

  def checkout
    @cart.cart_products.destroy_all
    redirect_to cart_path
  end

  def empty
    @cart.cart_products.destroy_all
    redirect_to cart_path, notice: 'Cart emptied successfully.'
  end

  private

  def set_cart
    @cart = current_user.cart
  end

  def calculate_total_amount(cart_products)
    total_amount = 0
    cart_products.each do |item|
      price = item.product.price || 0
      quantity = item.quantity || 0
      total_amount += price * quantity
    end
    total_amount
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ECOM</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%# <%= javascript_include_tag 'rails-ujs' %>
</head>
<body>

<%# add bootstrap %>
<%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>

<%= render partial: "shared/topbar" %>
<%= yield %>

</body>
</html>

app/views/shared/_topbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Home', products_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
          </li>
          <% if current_user && current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'Add Product', new_product_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Products', products_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Addresses', addresses_path, class: "nav-link" %>
          </li>
          <% unless current_user && current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'My Cart', cart_path(current_user.cart), class: "nav-link" %>
            </li>
          <% end %>
          <% unless current_user && current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'My Orders', orders_path, class: "nav-link" %>
            </li>
          <% end %>
          <% unless current_user && current_user.admin? %>
            <li class = "nav-item">
              <%= link_to 'My payments', payments_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= current_user.name%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>